spring:
  datasource:
    url: jdbc:mysql://bt2.dytomh.top:3307/kyleData?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&&zeroDateTimeBehavior=CONVERT_TO_NULL&&serverTimezone=GMT%2B8
    username: kyle
    password: ozi3enjvx662
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    suffix: .html
  redis:
   # host: 172.18.27.108
    host: 172.26.89.188
    password: qjf666@
    port: 6378
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    mybatis-plus:
      configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        mybatis-plus:
          type-aliases-package: org.qiujf
server:
  port: 34002


