spring:
  datasource:
    url: jdbc:mysql://bt.dytomh.top:3307/kyleData?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&&zeroDateTimeBehavior=CONVERT_TO_NULL&&serverTimezone=GMT%2B8
    username: kyleData
    password: NPKWeNGCeDGE5i5A
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    mybatis-plus:
      configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        mybatis-plus:
          type-aliases-package: org.qiujf.entity.po